export const ALL_POKEMONS = 'ALL_POKEMONS';
export const SORT_POKEMON = 'SORT_POKEMON';
export const SORT_ATTACK_LEVEL = 'SORT_ATTACK_LEVEL';
export const SORT_DEFENSE_LEVEL = "SORT_DEFENSE_LEVEL";
export const SORT_SPEED_LEVEL = "SORT_SPEED_LEVEL";
export const LEGENDARY_POKE = "LEGENDARY_POKE";
export const DELETE_POKEMON = 'DELETE_POKEMON';
export const DELETE_POKEMON_ERROR = 'DELETE_POKEMON_ERROR';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';



